# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 726baeda-md-taco
  namespace: 726baeda
spec:
  template:
    spec: {}
